module.exports = {
    'array-callback-return': 'error',
    'arrow-body-style': ['error', 'as-needed'],
    'block-scoped-var': 'error',
    'eol-last': 'error',
    'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],
    'no-await-in-loop': 'warn',
    'no-console': 'warn',
    'no-constructor-return': 'error',
    'no-debugger': 'error',
    'no-dupe-class-members': 'off',
    'no-empty-pattern': 'off',
    'no-extra-boolean-cast': 'error',
    'no-loop-func': 'error',
    'no-promise-executor-return': 'error',
    'no-restricted-properties': ['error'],
    'no-sequences': 'error',
    'no-template-curly-in-string': 'error',
    'no-trailing-spaces': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unreachable-loop': 'error',
    'no-unused-vars': 'error',
    'no-unused-expressions': ['error'],
    'no-useless-concat': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'object-shorthand': 'error',
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-destructuring': 'warn',
    'prefer-numeric-literals': 'error',
    'prefer-regex-literals': 'error',
    'prefer-template': 'error',
    'require-atomic-updates': 'warn',
    'require-await': 'warn',
    'unused-imports/no-unused-imports': 'error',
    complexity: 'error',
    curly: ['error', 'all'],
    eqeqeq: 'error',
    quotes: ['error', 'single', { avoidEscape: true }],
};
