name: CI
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      redis-cluster:
        image: grokzen/redis-cluster:latest
        ports:
          - 7000-7005:7000-7005
    steps:
      - uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
